# copy to configview.ini and set the configuration path
[format usermgr]
# description is optional

[config usermgr test]
path = ../wiki2user/output/ini
archive = archive
reports = reports
# description is optional

[server]
host = 127.0.0.1
port = 8080

[logging console]
log_level = INFO

[logging pipe]
log_level = INFO
