# copy to storeview.ini, relative database paths use this file's directory
[index]
database = D:/db/storeindex-test.db

[server]
bind = 127.0.0.1
port = 8080
auto_refresh = 10s
detail_link = https://leni.epd.de/detail/doc{src_id}/{src_rev}

[logging console]
log_level = INFO
color_mode = auto

[logging pipe]
log_level = INFO

# [app]
# max_runtime = 8h
