# copy to wikipush.ini and adjust local values
# see user-docs/settings.md for details

[logging]
/asyncio        = WARNING

[logging console]
log_level       = INFO

[logging pipe]
log_level       = INFO

[logging file]
log_file        = wikipush.log
log_level       = DEBUG

[mediawiki]
api             = https://example.org/w/api.php
username        = wikipush
password        = bot-password

[input]
path            = input

# one direct input directory per target namespace
[pages]
config          = config
dist            = dist

[push]
check_case      = true
summary         = wikipush: update from local Wikitext
