#   wikiread.example.ini
#
#   copy to wikiread.ini and adjust local values as needed
#   see user-docs/settings.md for details

[logging]
/asyncio        = WARNING

[logging console]
log_level       = INFO

[logging pipe]
log_level       = INFO

[logging file]
log_file        = wikiread.log
log_level       = DEBUG

#=========================================================================
#   MediaWiki connection
#-------------------------------------------------------------------------
[mediawiki]
api             = https://example.org/w/api.php
username        = wikiread
password        = bot-password

#=========================================================================
#   local output
#-------------------------------------------------------------------------
[output]
path            = output

#=========================================================================
#   page selection
#-------------------------------------------------------------------------
[pages]
legacy          = keywords, stichworte
config          = config/*

#=========================================================================
#   continuous operation
#-------------------------------------------------------------------------
[watch]
poll            = 1min
backoff         = 10s
backoff_max     = 5min
