#   storepack.example.ini
#   see user-docs/settings.md for details
#=========================================================================
#   logging
#-------------------------------------------------------------------------
#   per-logger level overrides; relative names prefixed with app name

[logging]
# runner = debug                       # relative: storepack.runner

[logging file]
log_file    	= storepack.log

#=========================================================================
#   message store settings
#-------------------------------------------------------------------------
[store]
path            = d:/store              # existing store path
match           = *
min_age         = 48h
